[build]
  functions = "func"

[[redirects]]
  from = "/links"
  to = "links/links.html"
  status = 200

[[redirects]]
  from = "/yt"
  to = "https://youtube.com/@jakineru"
  status = 301

[[redirects]]
  from = "/"
  to = "https://ayo.so/jaki"
  status = 301

[[redirects]]
  from = "/queso"
  to = "queso/queso.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "404/404.html"
  status = 404
