[build]
  functions = "func"

[[redirects]]
  from = "/links"
  to = "links/links.html"
  status = 200

[[redirects]]
  from = "/yt"
  to = "https://youtube.com/@jakineru"
  status = 301

[[redirects]]
  from = "yt.jaki.uy/*"
  to = "https://youtube.com/@jakineru"
  status = 301
  force = true

[[redirects]]
  from = "/donar"
  to = "https://paypal.me/jaki616"
  status = 301
  force = true

[[redirects]]
  from = "/pay"
  to = "https://paypal.me/jaki616"
  status = 301
  force = true

[[redirects]]
  from = "/queso"
  to = "queso/queso.html"
  status = 200

[[redirects]]
  from = "/phpmyadmin"
  to = "soulhem.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "404/404.html"
  status = 404

[[redirects]]
  from = "/spty"
  to = "https://open.spotify.com/playlist/1Delr3lDNT6L7siZT6pqzH"
  status = 301
  force = true